"""
Django settings for Auction project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'erqai^^ta^0fo+0u(p)g5!ailsz!r-)-l=e)g(xz+fvkr=sx=l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'auctionapp.apps.AuctionappConfig',
    'accounts.apps.AccountsConfig',
    'auctionItem.apps.AuctionitemConfig',
    'django.contrib.humanize',
    'blog.apps.BlogConfig',
    'taggit',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Auction.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'Auction.wsgi.application'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  
        'NAME': BASE_DIR / 'db.sqlite3',   
    }
}


# Password validation
# https://docsu.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


#channels config


ASGI_APPLICATION = 'Auction.routing.application'


CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT= os.path.join(BASE_DIR,'static')  #useful while deploying project 

STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'Auction/static')   #python manage.py help, python manage.py collectstatic
]

#Media url
MEDIA_ROOT=os.path.join(BASE_DIR,'media')
MEDIA_URL='/media/'

#messages

from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger',   
}

#Email configuraion


EMAIL_HOST='smtp.gmail.com'
EMAIL_HOST_USER='melzpereira0509@gmail.com'
EMAIL_HOST_PASSWORD='###############'
EMAIL_PORT=587
EMAIL_USE_TLS=True


#testing purpose email
# (env) C:\Users\Melody vilas pereira\Desktop\Django+projects\Aukshan>python manage.py shell
# Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)] on win32
# Type "help", "copyright", "credits" or "license" for more information.
# (InteractiveConsole)
# >>> from django.core.mail import send_mail
# >>> send_mail
# <function send_mail at 0x03920ED0>
# >>> send_mail('Django mail','This email was send using django for testing purpose only','melzpereira0509@gmail.com',['melzpereira0509@gmail.com'],fail_silently=False)
# Content-Type: text/plain; charset="utf-8"
# MIME-Version: 1.0
# Content-Transfer-Encoding: 7bit
# Subject: Django mail
# From: melzpereira0509@gmail.com
# To: melzpereira0509@gmail.com
# Date: Thu, 15 Oct 2020 05:46:17 -0000
# Message-ID: <160274077769.26828.14794922099455928566@melody>

# This email was send using django for testing purpose only
# -------------------------------------------------------------------------------
# 1
# >>>