# Generated by Django 3.1.1 on 2020-09-27 12:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('contact_no', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('year_dated', models.DateTimeField()),
                ('is_live', models.BooleanField(default=False)),
                ('base_price', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('main_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_trending', models.BooleanField(default=False)),
                ('year_published', models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 27, 18, 4, 58, 950358))),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auctionItem.seller')),
            ],
        ),
    ]
