# Generated by Django 3.1.1 on 2020-10-09 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionItem', '0002_auto_20201006_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='on_banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='photo4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='year_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 9, 18, 30, 36, 724956)),
        ),
    ]
