# Generated by Django 3.1.1 on 2020-10-18 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionItem', '0003_auto_20201009_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='year_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 18, 8, 51, 39, 134787)),
        ),
    ]
