# Generated by Django 3.1.1 on 2020-10-18 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionItem', '0004_auto_20201018_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='year_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 18, 15, 51, 4, 561479)),
        ),
    ]
