# Generated by Django 3.1.3 on 2020-11-14 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionItem', '0006_auto_20201020_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='year_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 11, 55, 39, 230334)),
        ),
    ]
