# Generated by Django 3.1.3 on 2020-11-14 11:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctionItem', '0007_auto_20201114_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('cap_time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lot',
            name='year_dated',
        ),
        migrations.AddField(
            model_name='lot',
            name='current_price',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='base_price',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lot',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='auctionItem.category'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='main_photo',
            field=models.ImageField(upload_to='photos/main/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='photos/optional/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='photos/optional/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='photos/optional/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='photo4',
            field=models.ImageField(blank=True, upload_to='photos/optional/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='year_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 16, 50, 32, 117732)),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_photo',
            field=models.ImageField(upload_to='photos/seller/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auctionItem.auction')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionItem.seller')),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auctionItem.lot'),
        ),
    ]
