# Generated by Django 3.1.3 on 2020-11-22 08:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctionItem', '0011_auto_20201114_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author_messsages', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lot',
            name='year_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 13, 49, 43, 398227)),
        ),
    ]
