# Generated by Django 3.1.3 on 2020-11-22 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionItem', '0012_auto_20201122_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='year_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 15, 5, 0, 128601)),
        ),
    ]
