# Generated by Django 3.1.3 on 2020-11-22 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionItem', '0013_auto_20201122_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='year_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 15, 54, 2, 464006)),
        ),
        migrations.AlterField(
            model_name='message',
            name='price',
            field=models.TextField(),
        ),
    ]
