# Generated by Django 3.1.3 on 2020-11-22 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionItem', '0014_auto_20201122_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='cap_time',
            new_name='curr_time',
        ),
        migrations.AlterField(
            model_name='lot',
            name='year_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 17, 0, 58, 116498)),
        ),
    ]
