# Generated by Django 3.1.3 on 2020-11-22 12:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctionItem', '0015_auto_20201122_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctionItem.lot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lot',
            name='year_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 17, 52, 34, 54481)),
        ),
    ]
