# Generated by Django 3.1.3 on 2020-11-22 12:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctionItem', '0016_auto_20201122_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='year_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 18, 17, 42, 475930)),
        ),
        migrations.AlterField(
            model_name='message',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionItem.auction'),
        ),
    ]
