# Generated by Django 3.1.3 on 2020-11-22 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionItem', '0017_auto_20201122_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='year_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 18, 17, 51, 326500)),
        ),
    ]
