# Generated by Django 3.1.3 on 2020-11-22 15:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctionItem', '0019_auto_20201122_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='year_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 20, 45, 2, 18600)),
        ),
        migrations.AlterField(
            model_name='message',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auctionItem.auction'),
        ),
    ]
