# Generated by Django 3.1.3 on 2020-11-26 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionItem', '0022_auto_20201124_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='time_stamp',
            new_name='timecap',
        ),
        migrations.AlterField(
            model_name='lot',
            name='year_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 11, 59, 33, 28664)),
        ),
    ]
